### PR TITLE
List.md Question

### PR DESCRIPTION
**Pull request by CrossOut4**
Can someone add all of my uploaded code files to the list.md branch? I see no no codes have been added to the list in a long time and i do not know how to do it. It only lets me upload a file to the master list and as you can see it looks really cluttered and needs fixing.

### CODE REVIEW

**Comment by RikuNoctis** [comment]
I see what the issue was. Sorry.

**Comment by CrossOut4** [comment]
Its ok. I also should have made it an issue and not a pull request i think. Hopefully someone can add my files soon.

**Comment by RikuNoctis** [comment]
I'm on it now, though I think you can now just make a pull request from your fork with the files added.

**Comment by CrossOut4** [comment]
i didnt know i could do it that way. I need to learn who to do that for future uploads. you see i added the files to this https://github.com/vaass95/vitacheat wihch is forked from this one. I think someone on the Vaass95 needs to update it there as well? or are both updated becasue they are linked?

**Comment by RikuNoctis** [comment]
> i didnt know i could do it that way. I need to learn who to do that for future uploads. you see i added the files to this https://github.com/vaass95/vitacheat wihch is forked from this one. I think someone on the Vaass95 needs to update it there as well? or are both updated becasue they are linked?

You basically fork (make your own copy) of the repo with the "Fork" button above. Then, on your copy, you can go to the desired folder (in this case the 'db' folder) and upload your new files there (once you are on the correct folder you can use the 'Upload File' button shown there). Now, once you have added or changed all of the files you want to contribute to you can make a pull request, which is basically adding anything you added or changed on your copy to the master branch, which is roah's repo.

This contribution is then reviewed by any of the collaborators, which in this case could be me, so it is accepted.

Other forks would probably need to be update so they have whatever was in the master branch (roah's) plus any of the changes made recently, like your contributions (because there can be many forks, from many users with different changes here and there).

**Comment by CrossOut4** [comment]
I think see now. I now have my own copy of roahs database. Do i need to re upload all of my files again then?

**Comment by RikuNoctis** [comment]
> I think see now. I now have my own copy of roahs database. Do i need to re upload all of my files again then?

If you want to try, yes. I already have your files ready, BTW. 
image

To make your pull request, first go to the 'db' folder on your fork and upload the files as I have them on my screenshot. The 'db' folder is where we put the .PSV files, so extensions like .RAR or .ZIP should be avoided.

After that just go your fork's main page and click the "'Pull request" button (you'll see the difference between each branch there too, indicating what changes have been made between them). 
image

After that, it will appear in the Pull Requests section from the main repo, where I can approve it and merge the changes.

**Comment by CrossOut4** [comment]
In this case can i ask you to add them? i have deleted some of this files and do not have all of them. I will remmeber this guide you gave me in furure when i upload more cheats. There are a lot more codes i need to add. I think the mistake i was making was adding them to the master branch and not the db folder instead.

**Comment by RikuNoctis** [comment]
> In this case can i ask you to add them? i have deleted some of this files and do not have all of them. I will remmeber this guide you gave me in furure when i upload more cheats. There are a lot more codes i need to add. I think the mistake i was making was adding them to the master branch and not the db folder instead.

Sure, no problem. From now you can add the files to your own fork, edit the files if you need to, and so on. Once you are okay with how they are you can then submit a pull request, it will get approved and appear in the master branch, so your fork and the master now have the same stuff.

**Comment by CrossOut4** [comment]
That is great, thanks for the help.

**Comment by CrossOut4** [comment]
Did you add the codes yet? I am working on getting a load of new ones that have been made recently so ill add those ones myself.

**Comment by RikuNoctis** [comment]
> Did you add the codes yet? I am working on getting a load of new ones that have been made recently so ill add those ones myself.

Yeah, I added them at the time. They are already on the 'db' folder in the repo.

**Comment by CrossOut4** [comment]
Hello again. I notice that on my version of the repository the new files are not there but they are on the roah version. what did i do wrong for them not to show up?

**Pull request merged**
