### PR TITLE
Geometry Wars 3 v1.00

### PR DESCRIPTION
**Pull request by xJam-es**
Geometry Wars 3 Cheats.
Region EU/AU
I've tested these multiple times and they seem pretty stable.

PS. thanks for the shout out in the Wiki ;)

### CODE REVIEW

**Comment by r0ah** [comment]
Thanks for the codes. Added to the db.

**Comment by r0ah** [comment]
That's pretty neat btw, defining pointer code like a variable so you could it anywhere.

**Comment by r0ah** [comment]
I added you as collaborator, thanks for your tempar tools.

**Comment by xJam-es** [comment]
Thanks :)
Yes i took a lazy approach while i was finding the pointers and just moved them to a fixed location each time i wanted to try one so i didn't have to change all my cheat codes also.

**Pull request merged**
